<?php
// submit.php

session_start();
header('Content-Type: application/json'); // Crucial: tell browser to expect JSON

// Basic input sanitization
function sanitize_input($data) {
    $data = trim($data);
    $data = stripslashes($data);
    $data = htmlspecialchars($data);
    return $data;
}

// Retrieve data including the order_id generated by JavaScript
$order_id = sanitize_input($_POST['order_id'] ?? 'N/A'); // Get order ID from JS
$customer_name = sanitize_input($_POST['customer_name'] ?? '');
$address = sanitize_input($_POST['address'] ?? '');

// MODIFIED: Retrieve phone_number and construct contact_number
$phone_number_raw = sanitize_input($_POST['phone_number'] ?? ''); // This will be the 10 digits
$contact_number = '+63' . $phone_number_raw; // Prepend the Philippine country code

$delivery_date = sanitize_input($_POST['delivery_date'] ?? '');
$delivery_type = sanitize_input($_POST['delivery_type'] ?? '');

$cake_design_name = sanitize_input($_POST['cake_design_name'] ?? '');
$cake_design = sanitize_input($_POST['cake_design'] ?? '');
$payment_method = sanitize_input($_POST['payment_method'] ?? '');

$layers = isset($_POST['layers']) ? array_map('sanitize_input', $_POST['layers']) : [];
$toppings = isset($_POST['toppings']) ? array_map('sanitize_input', $_POST['toppings']) : [];


// --- Artist Assignment (Server-side) ---
$artist_assigned = 'N/A'; // Default

// Define available artists (based on artist_id table)
$artists_list = [
    'A123: Nova Sweetz',
    'A456: Cosmo Bakes',
    'A789: Stella Swirls' // If you have more artists
];

// If specific designs have preferred artists from the bridge table
$cake_artist_map = [
    'Galactic Chocolate' => 'A123: Nova Sweetz',
    'Red Velvet Meteor' => 'A456: Cosmo Bakes',
    'Matcha Nebula' => 'A456: Cosmo Bakes', // Using A456 as a primary for Matcha as per example
];

if (isset($cake_artist_map[$cake_design])) {
    $artist_assigned = $cake_artist_map[$cake_design];
} else {
    // If no specific mapping or a different design, assign randomly from the list
    $artist_assigned = $artists_list[array_rand($artists_list)];
}


// --- Simulate Database Storage ---
// In a real application, you would connect to your MySQL database here
// using PDO or MySQLi prepared statements to insert this data.
// For demonstration, we'll store it in a session.

$_SESSION['order_details'] = [
    'order_id' => $order_id,
    'customer_name' => $customer_name,
    'address' => $address,
    'contact_number' => $contact_number, // Store the combined '+63' + phone number
    'delivery_date' => $delivery_date,
    'delivery_type' => $delivery_type,
    'cake_design_name' => $cake_design_name,
    'cake_design' => $cake_design,
    'layers' => implode(', ', $layers),
    'toppings' => implode(', ', $toppings),
    'artist_assigned' => $artist_assigned,
    'payment_method' => $payment_method
];

// Return a JSON response
echo json_encode(['success' => true, 'message' => 'Order successfully processed!', 'orderId' => $order_id]);
exit();
?>
